/**
 * Faithful port of R's grDevices::colorRampPalette(anchors)(n).
 *
 * Spec §13: "The domain ramps in §6.4 must match rscripts/build_scores.R:317–325
 * character for character. If the internal leaflet review maps and the dashboard
 * disagree on colour, every conversation about the data turns into a conversation
 * about the tool."
 *
 * Two details are load-bearing and were confirmed against real R output:
 *
 *  1. R normalises to [0,1] (col2rgb/255), interpolates there, then multiplies
 *     back by 255. That roundtrip leaves float error which changes the result:
 *     blue interpolates to 195.999999999999972, not 196.
 *  2. rgb(..., maxColorValue = 255) TRUNCATES, it does not round. So the value
 *     above becomes 195, and 198.5 becomes 198.
 *
 * Reproducing the arithmetic in the same order gives bit-identical results,
 * since both R and JS use IEEE 754 doubles. Pinned in colorRamp.test.ts against
 * values generated by R itself.
 */

function parseHex(hex) {
  const h = hex.replace('#', '');
  return [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
  ];
}

/** Evenly spaced positions with the endpoint pinned exactly, as R's seq.int does. */
function seq(n) {
  if (n === 1) return [0];
  const by = 1 / (n - 1);
  const out = Array.from({ length: n }, (_, i) => i * by);
  out[n - 1] = 1;
  return out;
}

function toHex(rgb) {
  return `#${rgb.map((v) => v.toString(16).padStart(2, '0').toUpperCase()).join('')}`;
}

export function colorRampPalette(anchors, n) {
  if (n < 1) return [];

  // col2rgb(...) / 255
  const stops = anchors.map((a) => parseHex(a).map((v) => v / 255));
  if (n === 1) return [toHex(stops[0].map((v) => Math.floor(v * 255)))];

  const x = seq(stops.length);
  const u = seq(n);

  return u.map((v) => {
    // A sample landing exactly on an anchor takes that anchor's value untouched.
    // approxfun does this, and it matters: interpolating to frac === 1 leaves
    // 28.999999999999996 where the anchor holds exactly 29, and truncation then
    // costs a whole step.
    const exact = x.indexOf(v);
    if (exact !== -1) {
      return toHex(stops[exact].map((y) => Math.floor(y * 255)));
    }

    let i = 0;
    while (i < x.length - 2 && v >= x[i + 1]) i++;
    const j = i + 1;

    const channels = [0, 1, 2].map((c) => {
      const yi = stops[i][c];
      const yj = stops[j][c];
      // R's approx1: y[i] + (y[j] - y[i]) * ((v - x[i]) / (x[j] - x[i]))
      const value = (yi + (yj - yi) * ((v - x[i]) / (x[j] - x[i]))) * 255;
      // rgb(maxColorValue = 255) truncates.
      return Math.floor(value);
    });
    return toHex(channels);
  });
}
