// Extract "Build Spec.dc.html" to docs/BUILD-SPEC.md.
//
// The canvas is the source of truth. This markdown exists so the spec is
// diffable in review and greppable from code comments (§ references all over
// src/ point at it). Regenerate after any spec change:
//     node scripts/extract-spec.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(ROOT, 'Build Spec.dc.html');
const OUT = resolve(ROOT, 'docs/BUILD-SPEC.md');

const ENTITIES = {
  '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'",
  '&nbsp;': ' ', '&mdash;': '—', '&ndash;': '–', '&rsquo;': '’',
  '&lsquo;': '‘', '&ldquo;': '“', '&rdquo;': '”', '&times;': '×',
};
const unescape = (s) =>
  s.replace(/&[a-z#0-9]+;/gi, (m) => ENTITIES[m] ?? m);

const stripTags = (s) => unescape(s.replace(/<[^>]+>/g, '')).replace(/\s+/g, ' ').trim();

let s = readFileSync(SRC, 'utf8');
s = s.replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/g, '');
s = s.replace(/<head[\s\S]*?<\/head>/g, '');

// Tables → markdown
s = s.replace(/<table[^>]*>[\s\S]*?<\/table>/g, (table) => {
  const rows = [...table.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/g)].map((m) =>
    [...m[1].matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/g)].map((c) => stripTags(c[1])),
  ).filter((r) => r.length);
  if (!rows.length) return '';
  const width = Math.max(...rows.map((r) => r.length));
  const pad = (r) => [...r, ...Array(width - r.length).fill('')];
  const lines = [`| ${pad(rows[0]).join(' | ')} |`, `|${'---|'.repeat(width)}`];
  for (const r of rows.slice(1)) lines.push(`| ${pad(r).join(' | ')} |`);
  return `\n\n${lines.join('\n')}\n\n`;
});

for (const [tag, prefix] of [['h1', '# '], ['h2', '## '], ['h3', '### '], ['h4', '#### ']]) {
  s = s.replace(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`, 'g'),
    (_, inner) => `\n\n${prefix}${stripTags(inner)}\n\n`);
}
// A <li> that wraps headings or a table is a layout container, not a list item —
// bulleting it would swallow a whole section into one line.
s = s.replace(/<li[^>]*>([\s\S]*?)<\/li>/g, (_, inner) => {
  if (/^\s*#{1,4}\s|\n#{1,4}\s|\n\|/.test(inner)) return `\n${inner}\n`;
  return `\n- ${stripTags(inner)}`;
});
s = s.replace(/<p[^>]*>([\s\S]*?)<\/p>/g, (_, i) => {
  const t = stripTags(i);
  return t ? `\n\n${t}\n\n` : '\n';
});
s = s.replace(/<[^>]+>/g, '');
s = unescape(s);

// Collapse the whitespace the HTML indentation leaves behind, without touching
// table rows or list items.
s = s
  .split('\n')
  .map((line) => (line.trim().startsWith('|') ? line.trim() : line.replace(/\s+/g, ' ').trim()))
  .join('\n')
  .replace(/\n{3,}/g, '\n\n')
  .trim();

const header = `<!--
  GENERATED from "Build Spec.dc.html" — do not edit this file by hand.
  The canvas is the source of truth; this markdown exists so the spec is
  diffable in review and greppable from the § references in src/.
  Regenerate: node scripts/extract-spec.mjs
-->
`;

writeFileSync(OUT, `${header}\n${s}\n`);
console.log(`docs/BUILD-SPEC.md — ${s.split(/\s+/).length} words, ${s.split('\n').length} lines`);
